[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mimicapi"
version = "0.0.0"
description = "MimicDB API"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["mimicapi*", "mimicrag_ingestion*", "mimicrag_dev*", "mimicrag_memory*"]
